#!/bin/bash

#########################################################
#
# save
#   genで作成されたファイルをsolvedフォルダに保存する。
#
#   2020.06.24
#
#########################################################

COMMAND=$(basename "$0")

echo {abc*,arc*,agc*,yuki*,joi*,chokudai*,kupc*,dfs*} \
| tr " " "\n" \
| while read DIR;do
    [[ -e ${DIR}/main.cpp ]] && {
        cp ${DIR}/main.cpp solved/${DIR}.cpp
    }
done