version: '3.3'

services:
  atcoder:
    build:
      context: .
      args:
        - GIT_USER
        - GITHUB_TOKEN
    volumes:
      - ..:/AtCoder
    working_dir: /
    tty: true
    # to use gdb
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      